//! Kinematics and dynamics via Pinocchio, linked through a C-ABI shim
//! built from the pinokin C++ core — one numerics stack shared with the
//! Python client (which uses pinokin directly).
//!
//! The safe wrapper preallocates model/data at init and exposes
//! allocation-free `fk / jacobian / gravity / ik` calls suitable for the
//! RT thread and planner. Fixtures generated by pinokin's Python output
//! regression-test this crate (`tests/golden/kinematics/`).
//!
//! Follow-up: coal/hpp-fcl collision through the same shim (shape world,
//! plan-time trajectory checks) — see the collision section of the README.
