"""Regenerate the enum members in `python/par6/_par6.pyi`.

The extension builds its `IntEnum`s at module init from each wire enum's
`variants()` in par6-proto, which is what keeps them from drifting: there is
no transcription to fall out of date. A type stub cannot share that
property — it is read statically, by a checker that never imports anything —
so a stub whose enum bodies are `...` gives `ty` classes with no members and
turns every `ErrorCode.MOTN_NOT_HOMED` in the tree into an unresolved
attribute.

So the members are written into the stub from the same reflection, off the
BUILT extension rather than a second reading of the Rust. `test_stub.py`
fails when the file and the extension disagree.

    pixi run gen-stub            # rewrite it
    pixi run gen-stub --check    # fail if it is stale
"""

from __future__ import annotations

import enum
import importlib
import sys
from pathlib import Path

STUB = Path(__file__).resolve().parent.parent / "python" / "par6" / "_par6.pyi"
BEGIN = "# --- enum members: generated by scripts/gen_stub.py ---"
END = "# --- end enum members ---"


def render(mod: object | None = None) -> str:
    """The generated region, as it should appear in the stub.

    `mod` is the extension to reflect; by default the installed one. It is a
    parameter so the stub can be generated from a freshly built `.so` before
    the package is installed, which is the state a first build is in.
    """
    if mod is None:
        mod = importlib.import_module("par6._par6")
    names = [
        n
        for n in dir(mod)
        if isinstance(getattr(mod, n), type)
        and issubclass(getattr(mod, n), enum.IntEnum)
    ]
    blocks = []
    for name in sorted(names):
        cls = getattr(mod, name)
        doc = (cls.__doc__ or "").strip()
        lines = [f"class {name}(IntEnum):"]
        if doc:
            lines.append(f'    """{doc}"""')
            lines.append("")
        for member in cls:
            lines.append(f"    {member.name} = {member.value}")
        blocks.append("\n".join(lines))
    return "\n".join([BEGIN, "", "\n\n".join(blocks), "", END])


def current() -> str:
    text = STUB.read_text()
    start = text.index(BEGIN)
    stop = text.index(END) + len(END)
    return text[start:stop]


def main(argv: list[str] | None = None) -> int:
    check = "--check" in (argv if argv is not None else sys.argv[1:])
    text = STUB.read_text()
    if BEGIN not in text or END not in text:
        print(f"{STUB} has no generated region; add the markers first", file=sys.stderr)
        return 2
    start = text.index(BEGIN)
    stop = text.index(END) + len(END)
    new = text[:start] + render() + text[stop:]
    if new == text:
        print(f"{STUB.name} is up to date")
        return 0
    if check:
        print(
            f"{STUB.name} is stale: a wire enum changed and the stub was not "
            f"regenerated. Run `pixi run gen-stub`.",
            file=sys.stderr,
        )
        return 1
    STUB.write_text(new)
    print(f"regenerated {STUB.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
