#!/usr/bin/env python3
"""Generate the shared Q15 excitation tables; no plant model is involved.

Schroeder phases reduce multisine peaks (IEEE IT, 1970,
doi:10.1109/TIT.1970.1054411). Frequency coverage and weights are our
experiment choices, not a result from that paper. Version both consumers
when changing these tables or their sampling convention.
"""

import argparse
import math
from pathlib import Path
import struct

N = 1024


def table(first, last, focused=False):
    # Keep the 1.53 Hz spacing through the observed 19 Hz oscillation.
    # Anchor lines outside 10–40 Hz retain power without dominating the budget.
    weights = [
        (1.0 if 7 <= k <= 26 else 0.5 if k < 7 else 0.25) if focused else 1.0
        for k in range(first, last + 1)
    ]
    # Cumulative line power sets the phase curvature. Equal weights recover
    # -pi*i*(i-1)/count; weighted lines avoid a large peak from that flat design.
    phases = []
    phase = cumulative = 0.0
    power = sum(w * w for w in weights)
    for weight in weights:
        phases.append(phase)
        phase -= 2 * math.pi * cumulative / power
        cumulative += weight * weight
    values = [
        sum(
            weights[i] * math.cos(2 * math.pi * k * n / N + phases[i])
            for i, k in enumerate(range(first, last + 1))
        )
        for n in range(N)
    ]
    peak = max(map(abs, values))
    return [round(v / peak * 32767) for v in values]


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--firmware", type=Path, required=True)
    args = parser.parse_args()
    # 256 recorded samples/period: divisor 16 gives 3.05..61.04 Hz;
    # divisor 4 gives 36.62..701.90 Hz. Tables interpolate at 6250 Hz.
    tables = [table(2, 40, focused=True), table(6, 115)]
    root = Path(__file__).resolve().parents[1]
    blob = b"".join(struct.pack("<h", v) for row in tables for v in row)
    (root / "crates/par6-bus/src/spectral/periodic-q15.bin").write_bytes(blob)
    lines = [
        "// Generated by par6/scripts/periodic_waveforms.py; protocol version 2.",
        "#pragma once",
        "#include <stdint.h>",
        "static const int16_t PERIODIC_WAVE[2][1024] = {",
    ]
    for row in tables:
        lines.append("  {")
        for i in range(0, N, 16):
            lines.append("    " + ", ".join(map(str, row[i : i + 16])) + ",")
        lines.append("  },")
    lines.append("};")
    (args.firmware / "periodic_waveforms.h").write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
