"""Type surface of the compiled engine binding (`crates/par6-py`).

The extension is transport + preview only; the typed Python API lives in
:mod:`par6.client`. Composite results cross as plain dicts (see the
crate's `convert.rs` for the exact keys).
"""

from collections.abc import Awaitable
from typing import Any

NUM_JOINTS: int
MAX_JOG_DURATION_S: float

class RobotWireError(Exception):
    """A structured runtime refusal; ``args`` is the wire 6-tuple
    ``(command_index, code, title, cause, effect, remedy)``."""

def ping_blocking(host: str, port: int, timeout: float = 0.5) -> bool: ...
def make_wire_error(
    code: int, params: dict[str, str] | None = None
) -> tuple[int, int, str, str, str, str]: ...

class CoreClient:
    @staticmethod
    def connect(
        host: str,
        port: int,
        timeout: float,
        retries: int,
        status_transport: str,
        status_port: int,
        mcast_group: str,
        mcast_iface: str,
        status_unicast_host: str,
        mtu: int,
    ) -> Awaitable[CoreClient]: ...
    def close(self) -> None: ...
    def status_seq_gaps(self) -> int: ...
    def latest_status(self) -> dict[str, Any] | None: ...
    def status_after(
        self, last_seq: int, timeout: float
    ) -> Awaitable[dict[str, Any] | None]: ...
    def wait_command(self, index: int, timeout: float) -> Awaitable[bool]: ...
    # Queries: None when the runtime is unreachable.
    def ping(self) -> Awaitable[bool | None]: ...
    def angles(self) -> Awaitable[list[float] | None]: ...
    def pose(self, frame: int) -> Awaitable[list[float] | None]: ...
    def io(self) -> Awaitable[list[int] | None]: ...
    def joint_speeds(self) -> Awaitable[list[float] | None]: ...
    def status_query(self) -> Awaitable[dict[str, Any] | None]: ...
    def tools(self) -> Awaitable[dict[str, Any] | None]: ...
    def queue(self) -> Awaitable[dict[str, Any] | None]: ...
    def activity(self) -> Awaitable[dict[str, Any] | None]: ...
    def loop_stats(self) -> Awaitable[dict[str, Any] | None]: ...
    def reachable(self) -> Awaitable[dict[str, Any] | None]: ...
    def shapes(self) -> Awaitable[dict[str, Any] | None]: ...
    def profile(self) -> Awaitable[str | None]: ...
    def error(self) -> Awaitable[tuple | None]: ...
    def tcp_speed(self) -> Awaitable[float | None]: ...
    def tcp_offset(self) -> Awaitable[list[float] | None]: ...
    def tool_status(self) -> Awaitable[dict[str, Any] | None]: ...
    def is_simulator(self) -> Awaitable[bool | None]: ...
    # SYSTEM: 1 confirmed, 0 unconfirmed; raises RobotWireError on refusal.
    def reset(self) -> Awaitable[int]: ...
    def estop(self) -> Awaitable[int]: ...
    def safety_stop(self) -> Awaitable[int]: ...
    def set_gravity_comp(self, on: bool) -> Awaitable[int]: ...
    def pause(self, on: bool) -> Awaitable[int]: ...
    def stop(self, clear_queue: bool) -> Awaitable[int]: ...
    def write_io(self, port: int, value: int) -> Awaitable[int]: ...
    def simulator(self, on: bool) -> Awaitable[int]: ...
    def select_profile(self, profile: str) -> Awaitable[int]: ...
    def reset_state(self) -> Awaitable[int]: ...
    def connect_hardware(self, port: str) -> Awaitable[int]: ...
    def set_tcp_offset(self, x: float, y: float, z: float) -> Awaitable[int]: ...
    def set_shapes(self, shapes: list[dict[str, Any]]) -> Awaitable[int]: ...
    def set_completion_policy(self, policy: int) -> Awaitable[int]: ...
    def set_recipe(self, name: str) -> Awaitable[int]: ...
    # QUEUED: queue index >= 0, -1 unconfirmed; raises RobotWireError.
    def home(self) -> Awaitable[int]: ...
    def move_j(
        self,
        angles: list[float],
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
        rel: bool,
    ) -> Awaitable[int]: ...
    def move_j_pose(
        self,
        pose: list[float],
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
    ) -> Awaitable[int]: ...
    def move_l(
        self,
        pose: list[float],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
        rel: bool,
    ) -> Awaitable[int]: ...
    def move_c(
        self,
        via: list[float],
        end: list[float],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
    ) -> Awaitable[int]: ...
    def move_s(
        self,
        waypoints: list[list[float]],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
    ) -> Awaitable[int]: ...
    def move_p(
        self,
        waypoints: list[list[float]],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
    ) -> Awaitable[int]: ...
    def select_tool(
        self, tool_name: str, variant_key: str | None
    ) -> Awaitable[int]: ...
    def delay(self, seconds: float) -> Awaitable[int]: ...
    def checkpoint(self, label: str) -> Awaitable[int]: ...
    def tool_action(
        self, tool_key: str, action: str, params: list[Any]
    ) -> Awaitable[int]: ...
    # Fire-and-forget: 1 on send; raises on locally-invalid parameters.
    def servo_j(
        self, angles: list[float], speed: float | None, accel: float | None
    ) -> Awaitable[int]: ...
    def servo_j_pose(
        self, pose: list[float], speed: float | None, accel: float | None
    ) -> Awaitable[int]: ...
    def servo_l(
        self, pose: list[float], speed: float | None, accel: float | None
    ) -> Awaitable[int]: ...
    def jog_j(
        self, speeds: list[float], duration: float, accel: float | None
    ) -> Awaitable[int]: ...
    def jog_l(
        self, velocities: list[float], duration: float, frame: int, accel: float | None
    ) -> Awaitable[int]: ...
    def teleport(
        self, angles: list[float], tool_positions: list[float] | None
    ) -> Awaitable[int]: ...
    def reset_loop_stats(self) -> Awaitable[int]: ...
    def config_info(self) -> Awaitable[dict[str, Any] | None]: ...
    def payload(self) -> Awaitable[dict[str, Any] | None]: ...
    def set_payload(
        self, mass: float, com: list[float], inertia: list[float] | None = None
    ) -> Awaitable[int]: ...

class Preview:
    def __init__(
        self, config: str | None = None, assets: str | None = None
    ) -> None: ...
    def angles_rad(self) -> list[float]: ...
    def teleport_rad(self, q: list[float]) -> None: ...
    def homed(self) -> bool: ...
    def set_homed(self, homed: bool) -> None: ...
    def pose(self) -> list[float]: ...
    @staticmethod
    def profiles() -> list[str]: ...
    def tick_dt_s(self) -> float: ...
    def motion(self) -> dict[str, float]: ...
    def set_context(
        self, profile: str, tcp_offset_mm: list[float], policy: int
    ) -> None: ...
    def set_shapes(
        self, layer: str, shapes: list[dict[str, Any]]
    ) -> int | None: ...
    def preview_jog(
        self, speeds: list[float], duration: float, accel: float | None = None
    ) -> dict[str, Any]: ...
    def preview_program(self, cmds: list[dict[str, Any]]) -> list[dict[str, Any]]: ...

class TelemetryReader:
    def __init__(
        self, port: int, host: str = "127.0.0.1", group: str | None = None
    ) -> None: ...
    def recv(self, timeout: float = 1.0) -> dict[str, Any] | None: ...
    def drain(self) -> list[dict[str, Any]]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "TelemetryReader": ...
    def __exit__(self, *args: object) -> bool: ...
