"""Type surface of the compiled engine binding (`crates/par6-py`).

The extension is the whole engine: wire client, offline preview,
kinematics, collision world and config loader. The typed Python API in
:mod:`par6` is a shim over it and holds no numerics of its own.
Composite results cross as plain dicts (see the crate's `convert.rs`
for the exact keys).
"""

from collections.abc import Awaitable
from typing import Any

NUM_JOINTS: int
MAX_JOG_DURATION_S: float
COLLISION_CLEARANCE_M: float

class RobotWireError(Exception):
    """A structured runtime refusal; ``args`` is the wire 6-tuple
    ``(command_index, code, title, cause, effect, remedy)``."""

def ping_blocking(host: str, port: int, timeout: float = 0.5) -> bool: ...
def make_wire_error(
    code: int, params: dict[str, str] | None = None
) -> tuple[int, int, str, str, str, str]: ...

# ---- pose math (metres, radians; rpy intrinsic XYZ, the wire convention)
def matrix_to_xyzrpy(m: list[float]) -> list[float]: ...
def pose_matrix(xyz: list[float], rpy: list[float]) -> list[float]: ...
def compose_tool_frame(
    origin: list[float], rpy: list[float], offset: list[float]
) -> list[float]: ...
def frame_offset(urdf: str, from_frame: str, to_frame: str) -> list[float]: ...

class Config:
    def __init__(self, path: str | None = None) -> None: ...
    def path(self) -> str: ...
    def name(self) -> str: ...
    def joint_count(self) -> int: ...
    def joint_names(self) -> list[str]: ...
    def tick_dt_s(self) -> float: ...
    def park_pose_rad(self) -> list[float]: ...
    def active_gripper(self) -> str: ...
    def soft_limits_rad(self) -> list[tuple[float, float]]: ...
    def hard_limits_rad(self) -> list[tuple[float, float]]: ...
    def limits(self, mode: str) -> dict[str, list[float]]: ...
    def hardware_limits(self) -> dict[str, list[float]]: ...
    def jog_defaults(self) -> dict[str, Any]: ...
    def motion(self) -> dict[str, float | None]: ...
    def io_lines(self) -> tuple[list[str], list[str]]: ...
    def homing_ready_pose_rad(self) -> list[float]: ...
    def joints(self) -> list[dict[str, Any]]: ...
    def grippers(self) -> list[dict[str, Any]]: ...
    def variant(self, gripper_name: str) -> dict[str, str]: ...
    def installation_shapes(self) -> list[dict[str, Any]]: ...

class Kinematics:
    def __init__(
        self,
        urdf: str,
        ee_frame: str | None = None,
        tool_transform: list[float] | None = None,
        soft_limits: list[tuple[float, float]] | None = None,
    ) -> None: ...
    def nq_full(self) -> int: ...
    def fk(self, q: list[float]) -> list[float]: ...
    def tcp(self, q: list[float]) -> list[float]: ...
    def fk_batch(self, rows: list[list[float]]) -> list[list[float]]: ...
    def ik(self, seed: list[float], target: list[float]) -> list[float] | None: ...
    def ik_pose(
        self, seed: list[float], pose: list[float]
    ) -> dict[str, Any] | None: ...
    def ik_batch(
        self, poses: list[list[float]], seed: list[float]
    ) -> list[dict[str, Any] | None]: ...
    def violations(self, q: list[float]) -> list[int]: ...
    def jacobian(self, q: list[float]) -> list[list[float]]: ...
    def opw_parameters(self) -> dict[str, Any]: ...

class CollisionWorld:
    def __init__(
        self,
        urdf: str,
        package_dir: str | None = None,
        srdf: str | None = None,
        clearance: float = ...,
    ) -> None: ...
    def nq_full(self) -> int: ...
    def clearance(self) -> float: ...
    def scene_epoch(self) -> int: ...
    def pair_count(self) -> int: ...
    def set_layer(self, layer: str, shapes: list[dict[str, Any]]) -> int: ...
    def in_collision(self, q: list[float]) -> bool: ...
    def pairs(self, q: list[float]) -> list[tuple[str, str]]: ...
    def min_distance(self, q: list[float]) -> float: ...
    def check_path(self, rows: list[list[float]]) -> int: ...

class CoreClient:
    @staticmethod
    def connect(
        host: str | None = None,
        port: int | None = None,
        timeout: float | None = None,
        retries: int | None = None,
        status_transport: str | None = None,
        status_port: int | None = None,
        mcast_group: str | None = None,
        mcast_iface: str | None = None,
        status_unicast_host: str | None = None,
        mtu: int | None = None,
    ) -> Awaitable[CoreClient]: ...
    def endpoint(self) -> tuple[str, int]: ...
    def status_endpoint(self) -> tuple[str, int]: ...
    def close(self) -> None: ...
    def status_seq_gaps(self) -> int: ...
    def latest_status(self) -> dict[str, Any] | None: ...
    def status_after(
        self, last_seq: int, timeout: float
    ) -> Awaitable[dict[str, Any] | None]: ...
    def wait_command(self, index: int, timeout: float) -> Awaitable[bool]: ...
    def command_verdict(self, index: int) -> int | None: ...
    def wait_checkpoint(self, label: str, timeout: float) -> Awaitable[bool]: ...
    def wait_motion(
        self,
        timeout: float,
        settle_window: float,
        speed_threshold: float,
        angle_threshold: float,
        motion_start_timeout: float,
    ) -> Awaitable[bool]: ...
    def is_estop_pressed(self) -> Awaitable[bool]: ...
    def is_robot_stopped(self, threshold: float) -> Awaitable[bool]: ...
    def is_freedrive(self, timeout: float) -> Awaitable[bool]: ...
    # Queries: None when the runtime is unreachable.
    def ping(self) -> Awaitable[bool | None]: ...
    def angles(self) -> Awaitable[list[float] | None]: ...
    def pose(self, frame: int) -> Awaitable[list[float] | None]: ...
    def pose_xyzrpy(self, frame: int) -> Awaitable[list[float] | None]: ...
    def io(self) -> Awaitable[list[int] | None]: ...
    def joint_speeds(self) -> Awaitable[list[float] | None]: ...
    def status_query(self) -> Awaitable[dict[str, Any] | None]: ...
    def tools(self) -> Awaitable[dict[str, Any] | None]: ...
    def queue(self) -> Awaitable[dict[str, Any] | None]: ...
    def activity(self) -> Awaitable[dict[str, Any] | None]: ...
    def loop_stats(self) -> Awaitable[dict[str, Any] | None]: ...
    def reachable(self) -> Awaitable[dict[str, Any] | None]: ...
    def shapes(self) -> Awaitable[dict[str, Any] | None]: ...
    def profile(self) -> Awaitable[str | None]: ...
    def error(self) -> Awaitable[tuple | None]: ...
    def tcp_speed(self) -> Awaitable[float | None]: ...
    def tcp_offset(self) -> Awaitable[list[float] | None]: ...
    def tool_status(self) -> Awaitable[dict[str, Any] | None]: ...
    def is_simulator(self) -> Awaitable[bool | None]: ...
    # SYSTEM: 1 confirmed, 0 unconfirmed; raises RobotWireError on refusal.
    def reset(self) -> Awaitable[int]: ...
    def estop(self) -> Awaitable[int]: ...
    def set_gravity_comp(self, on: bool) -> Awaitable[int]: ...
    def pause(self, on: bool) -> Awaitable[int]: ...
    def stop(self, clear_queue: bool) -> Awaitable[int]: ...
    def write_io(self, port: int, value: int) -> Awaitable[int]: ...
    def simulator(self, on: bool) -> Awaitable[int]: ...
    def select_profile(self, profile: str) -> Awaitable[int]: ...
    def reset_state(self) -> Awaitable[int]: ...
    def connect_hardware(self, port: str) -> Awaitable[int]: ...
    def enter_flashing(self, assertion: str) -> Awaitable[int]: ...
    def exit_flashing(self) -> Awaitable[int]: ...
    def set_pid_gains(
        self,
        node: int,
        kpp: float,
        kpv: float,
        kiv: float,
        kpiq: float,
        kiiq: float,
        kp: float,
        kd: float,
        ilim_ma: float,
        velocity_limit_ticks_s: float,
        voltage_limit_mv: int,
    ) -> Awaitable[int]: ...
    def set_tcp_offset(self, x: float, y: float, z: float) -> Awaitable[int]: ...
    def set_shapes(self, shapes: list[dict[str, Any]]) -> Awaitable[int]: ...
    def set_completion_policy(self, policy: int) -> Awaitable[int]: ...
    def set_recipe(self, name: str) -> Awaitable[int]: ...
    # QUEUED: queue index >= 0, -1 unconfirmed; raises RobotWireError.
    def home(self, calibrate: bool = False) -> Awaitable[int]: ...
    def move_j(
        self,
        angles: list[float],
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
        rel: bool,
    ) -> Awaitable[int]: ...
    def move_j_pose(
        self,
        pose: list[float],
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
    ) -> Awaitable[int]: ...
    def move_l(
        self,
        pose: list[float],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
        rel: bool,
    ) -> Awaitable[int]: ...
    def move_c(
        self,
        via: list[float],
        end: list[float],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
        blend_radius: float | None,
        rel: bool = False,
    ) -> Awaitable[int]: ...
    def move_s(
        self,
        waypoints: list[list[float]],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
        rel: bool = False,
    ) -> Awaitable[int]: ...
    def move_p(
        self,
        waypoints: list[list[float]],
        frame: int,
        duration: float | None,
        speed: float | None,
        accel: float | None,
        rel: bool = False,
    ) -> Awaitable[int]: ...
    def select_tool(
        self, tool_name: str, variant_key: str | None
    ) -> Awaitable[int]: ...
    def delay(self, seconds: float) -> Awaitable[int]: ...
    def checkpoint(self, label: str) -> Awaitable[int]: ...
    def tool_action(
        self, tool_key: str, action: str, params: list[Any]
    ) -> Awaitable[int]: ...
    # Fire-and-forget: 1 on send; raises on locally-invalid parameters.
    def servo_j(
        self, angles: list[float], speed: float | None, accel: float | None
    ) -> Awaitable[int]: ...
    def servo_j_pose(
        self, pose: list[float], speed: float | None, accel: float | None
    ) -> Awaitable[int]: ...
    def servo_l(
        self, pose: list[float], speed: float | None, accel: float | None
    ) -> Awaitable[int]: ...
    def jog_j(
        self, speeds: list[float], duration: float, accel: float | None
    ) -> Awaitable[int]: ...
    def jog_l(
        self, velocities: list[float], duration: float, frame: int, accel: float | None
    ) -> Awaitable[int]: ...
    def teleport(
        self, angles: list[float], tool_positions: list[float] | None
    ) -> Awaitable[int]: ...
    def reset_loop_stats(self) -> Awaitable[int]: ...
    def config_info(self) -> Awaitable[dict[str, Any] | None]: ...
    def config_bundle(self) -> Awaitable[dict[str, Any] | None]: ...
    def payload(self) -> Awaitable[dict[str, Any] | None]: ...
    def set_payload(
        self, mass: float, com: list[float], inertia: list[float] | None = None
    ) -> Awaitable[int]: ...
    def identify_payload(
        self,
        config: str | None = None,
        assets: str | None = None,
        package_dir: str | None = None,
        spread: float = 0.5,
        ridge: float = 0.01,
        declare: bool = False,
    ) -> Awaitable[dict[str, Any]]: ...

class Preview:
    def __init__(
        self,
        config: str | None = None,
        assets: str | None = None,
        max_points: int = 200,
    ) -> None: ...
    def submit(self, command: dict[str, Any]) -> dict[str, Any] | None: ...
    def flush(self) -> dict[str, Any] | None: ...
    def angles_rad(self) -> list[float]: ...
    def angles_deg(self) -> list[float]: ...
    def pose_xyzrpy(self) -> list[float]: ...
    def place_rad(self, q: list[float]) -> None: ...
    def homed(self) -> bool: ...
    def set_homed(self, homed: bool) -> None: ...
    def pose(self) -> list[float]: ...
    @staticmethod
    def profiles() -> list[str]: ...
    def profile(self) -> str: ...
    def tcp_offset_mm(self) -> list[float]: ...
    def tool(self) -> tuple[str, str | None]: ...
    def tool_position(self) -> float: ...
    def tool_calibrated(self) -> bool: ...
    def io(self) -> list[int]: ...
    def queue(self) -> list[str]: ...
    def tick_dt_s(self) -> float: ...
    def motion(self) -> dict[str, float | None]: ...
    def homing_ready_pose_rad(self) -> list[float]: ...
    def set_shapes(self, layer: str, shapes: list[dict[str, Any]]) -> int | None: ...

class TelemetryReader:
    def __init__(
        self, port: int, host: str = "127.0.0.1", group: str | None = None
    ) -> None: ...
    def recv(self, timeout: float = 1.0) -> dict[str, Any] | None: ...
    def drain(self) -> list[dict[str, Any]]: ...
    def close(self) -> None: ...
    def __enter__(self) -> "TelemetryReader": ...
    def __exit__(self, *args: object) -> bool: ...
