"""Cross-language golden-vector conformance for protocol v2.

Decodes every vector under ``tests/golden/protocol`` (generated by the Rust
``par6-proto`` crate), cross-checks against the manifest expectations, and
re-encodes commands/replies/status with the Python packer to byte-compare
with the Rust encoder's output.
"""

from __future__ import annotations

import json
import math
from pathlib import Path

import pytest
from waldoctl.status import ActionState as WActionState
from waldoctl.tools import ToolState as WToolState

from par6.protocol import wire
from par6.protocol.constants import (
    COMMAND_CLASS,
    STATUS_LEN,
    ActionState,
    CmdType,
    CommandClass,
    MsgType,
    QueryType,
    ToolState,
)

GOLDEN_DIR = Path(__file__).resolve().parents[2] / "tests" / "golden" / "protocol"

with (GOLDEN_DIR / "manifest.json").open() as f:
    MANIFEST = json.load(f)

VECTORS = MANIFEST["vectors"]


def from_manifest(value):
    """Convert a manifest JSON value to its wire-object form (hex → bytes)."""
    if isinstance(value, dict):
        assert set(value) == {"__bin__"}, "only bin blobs are encoded as objects"
        return bytes.fromhex(value["__bin__"])
    if isinstance(value, list):
        return [from_manifest(v) for v in value]
    return value


def by_kind(kind: str) -> list[dict]:
    entries = [v for v in VECTORS if v["kind"] == kind]
    assert entries, f"manifest has no {kind} vectors"
    return entries


def read_bin(entry: dict) -> bytes:
    return (GOLDEN_DIR / entry["file"]).read_bytes()


@pytest.mark.parametrize(
    ("generated", "public"),
    [(ActionState, WActionState), (ToolState, WToolState)],
    ids=["action_state", "tool_state"],
)
def test_the_public_state_enums_carry_the_generated_wire_values(generated, public):
    """`par6.protocol` re-exports waldoctl's `ActionState`/`ToolState` rather
    than the ones generated from the Rust codec, so a decoded STATUS compares
    by identity against what a waldoctl consumer holds.  That substitution is
    only sound while the two agree member-for-member: if Rust ever renumbers a
    state, the wire would decode into a waldoctl member naming a different
    one, and nothing downstream would notice.
    """
    assert {m.name: m.value for m in generated} == {m.name: m.value for m in public}
    for member in generated:
        assert public(int(member)).name == member.name


def test_manifest_covers_every_command_and_class():
    cmds = {v["cmd"] for v in by_kind("command")}
    assert cmds == {c.name for c in CmdType}, "every command needs a golden vector"
    classes = {v["class"] for v in by_kind("command")}
    assert classes == {c.name for c in CommandClass}


@pytest.mark.parametrize("entry", by_kind("command"), ids=lambda e: e["name"])
def test_command_vectors(entry):
    blob = read_bin(entry)
    wire_arr = from_manifest(entry["wire"])

    # The manifest's declared tag/class must agree with the generated mirror.
    cmd = CmdType[entry["cmd"]]
    assert wire_arr[0] == cmd == entry["tag"]
    assert COMMAND_CLASS[cmd].name == entry["class"]

    # Python encoder must reproduce the Rust encoder's bytes exactly.
    assert wire.encode_wire(wire_arr) == blob
    assert wire.encode_command(cmd, entry["req_id"], wire_arr[2:]) == blob

    # Python decoder accepts the bytes and yields the manifest expectation.
    decoded_cmd, req_id, params = wire.decode_command(blob)
    assert decoded_cmd == cmd
    assert req_id == entry["req_id"]
    assert params == wire_arr[2:]

    # QUEUED commands carry their idempotency key as the first param.
    if COMMAND_CLASS[cmd] is CommandClass.QUEUED:
        assert params[0] == entry["idempotency_key"]
    else:
        assert entry["idempotency_key"] is None


@pytest.mark.parametrize("entry", by_kind("reply"), ids=lambda e: e["name"])
def test_reply_vectors(entry):
    blob = read_bin(entry)
    wire_arr = from_manifest(entry["wire"])
    assert wire.encode_wire(wire_arr) == blob

    msg_type, req_id, payload = wire.decode_reply(blob)
    assert msg_type == wire_arr[0]
    assert req_id == wire_arr[1]
    kind = entry["msg"]
    if kind == "OK":
        assert payload == (wire_arr[2] if len(wire_arr) > 2 else None)
    elif kind == "ERROR":
        assert msg_type is MsgType.ERROR
        assert payload == wire_arr[2]
        index, code, title, cause, effect, remedy = payload
        assert isinstance(code, int) and 10 <= code < 60
        assert title and cause and effect and remedy
    elif kind.startswith("RESPONSE/"):
        assert msg_type is MsgType.RESPONSE
        assert payload == wire_arr[2]
        assert QueryType(payload[0]).name == kind.split("/", 1)[1]
    elif kind == "COMPLETE":
        assert msg_type is MsgType.COMPLETE
        index, ok, detail = payload
        assert index == wire_arr[2]
        assert ok == wire_arr[3]
        assert detail == (wire_arr[4] if len(wire_arr) > 4 else None)
        if not ok:
            assert detail is not None, "failed COMPLETE must carry detail"
    else:
        pytest.fail(f"unknown reply kind {kind}")


@pytest.mark.parametrize("entry", by_kind("status"), ids=lambda e: e["name"])
def test_status_vectors(entry):
    blob = read_bin(entry)
    wire_arr = from_manifest(entry["wire"])
    assert wire.encode_wire(wire_arr) == blob
    assert len(wire_arr) >= STATUS_LEN

    buf = wire.StatusBuffer()
    assert wire.decode_status_bin_into(blob, buf) is True

    f = entry["fields"]
    assert buf.proto_version == f["proto_version"]
    assert buf.controller_id == f["controller_id"]
    assert buf.seq == f["seq"]
    assert buf.mono_time_ns == f["mono_time_ns"]
    assert buf.link_ok == f["link_ok"]
    assert buf.data_age_ms == f["data_age_ms"]
    assert buf.pose.tolist() == f["pose"]
    assert buf.angles.tolist() == f["angles"]
    assert buf.speeds.tolist() == f["speeds"]
    assert buf.io.tolist() == f["io"]
    assert buf.action_current == f["action_current"]
    assert buf.action_state == ActionState(f["action_state"])
    assert buf.joint_en.tolist() == f["joint_en"]
    assert buf.cart_en_wrf.tolist() == f["cart_en_wrf"]
    assert buf.cart_en_trf.tolist() == f["cart_en_trf"]
    assert buf.cart_en["WRF"] is buf.cart_en_wrf
    assert buf.executing_index == f["executing_index"]
    assert buf.completed_index == f["completed_index"]
    assert buf.last_checkpoint == f["last_checkpoint"]
    if f["error"] is None:
        assert buf.error is None
    else:
        assert buf.error is not None
        assert list(buf.error) == f["error"]
    assert buf.queued_segments == f["queued_segments"]
    assert buf.queued_duration == f["queued_duration"]
    assert buf.action_params == f["action_params"]
    if f["tool_status"] is None:
        assert buf.tool_status_present is False
    else:
        assert buf.tool_status_present is True
        ts = buf.tool_status
        key, state, engaged, part, fault, positions, channels, variant = f["tool_status"]
        assert ts.key == key
        assert ts.state == ToolState(state)
        assert ts.engaged == engaged
        assert ts.part_detected == part
        assert ts.fault_code == fault
        assert list(ts.positions) == positions
        assert list(ts.channels) == channels
        assert ts.variant_key == variant
    assert buf.tcp_speed == f["tcp_speed"]
    assert buf.simulator_active == f["simulator_active"]
    assert buf.collision_active == f["collision_active"]
    assert [list(p) for p in buf.collision_pairs] == f["collision_pairs"]
    assert buf.scene_epoch == f["scene_epoch"]
    assert buf.accepted_index == f["accepted_index"]
    assert buf.homed == f["homed"]


def test_status_decode_is_allocation_stable():
    """Repeated decodes reuse the same arrays (the zero-alloc contract)."""
    entry = next(v for v in by_kind("status") if v["name"] == "status_full")
    blob = read_bin(entry)
    buf = wire.StatusBuffer()
    pose_id, angles_id = id(buf.pose), id(buf.angles)
    for _ in range(3):
        assert wire.decode_status_bin_into(blob, buf)
    assert id(buf.pose) == pose_id and id(buf.angles) == angles_id
    assert not math.isnan(buf.pose[0])


def test_chunk_vectors_reassemble_to_the_inner_command():
    entries = sorted(by_kind("chunk"), key=lambda e: e["index"])
    assembled_hex = {e["assembled_hex"] for e in entries}
    assert len(assembled_hex) == 1
    expected_payload = bytes.fromhex(assembled_hex.pop())

    ra = wire.Reassembler(timeout_s=1.0)
    payload = None
    for e in entries:
        blob = read_bin(e)
        wire_arr = from_manifest(e["wire"])
        assert wire.encode_wire(wire_arr) == blob
        chunk = wire.decode_chunk(blob)
        assert chunk[:4] == (e["req_id"], e["transfer_id"], e["index"], e["total"])
        result = ra.push(chunk, now=0.0)
        if result is not None:
            payload = result
    assert payload == expected_payload

    cmd, req_id, params = wire.decode_command(payload)
    assert cmd.name == entries[0]["inner_cmd"]
    assert req_id == entries[0]["req_id"]
    assert len(params[1]) >= 2  # the bulk waypoint list survived reassembly

    # Splitting the payload the same way regenerates the golden envelopes.
    chunk_size = len(from_manifest(entries[0]["wire"])[5])
    split = wire.split_into_chunks(
        entries[0]["req_id"], entries[0]["transfer_id"], payload, chunk_size
    )
    assert split == [read_bin(e) for e in entries]


def test_chunk_reassembler_expires_stale_transfers():
    ra = wire.Reassembler(timeout_s=0.5)
    ra.push((1, 42, 0, 2, b"aa"), now=0.0)
    assert ra.expire(now=0.4) == []
    assert ra.expire(now=0.6) == [42]
    # after expiry the transfer restarts from scratch
    assert ra.push((1, 42, 1, 2, b"bb"), now=1.0) is None


@pytest.mark.parametrize("entry", by_kind("malformed"), ids=lambda e: e["name"])
def test_malformed_vectors(entry):
    blob = read_bin(entry)
    target = entry["target"]
    if target == "command":
        with pytest.raises(wire.ProtocolError):
            wire.decode_command(blob)
    elif target == "reply":
        with pytest.raises(wire.ProtocolError):
            wire.decode_reply(blob)
    elif target == "status":
        buf = wire.StatusBuffer()
        assert wire.decode_status_bin_into(blob, buf) is False
    else:
        pytest.fail(f"unknown malformed target {target}")


def test_encode_command_rejects_what_the_wire_rejects():
    """Client-side validation matches decode-side validation."""
    with pytest.raises(wire.ProtocolError):
        wire.encode_command(CmdType.DELAY, 1, [5, float("nan")])
    with pytest.raises(wire.ProtocolError):
        wire.encode_command(CmdType.WRITE_IO, 1, [9, 0])
    with pytest.raises(wire.ProtocolError):
        # duration and speed are mutually exclusive
        wire.encode_command(
            CmdType.MOVE_J, 1, [5, [0.0] * 6, 1.0, 0.5, None, None, False]
        )
    with pytest.raises(wire.ProtocolError):
        # queued commands require the idempotency key param
        wire.encode_command(CmdType.HOME, 1, [])
