//! Golden conformance for the collision world: [`Collision`] must reproduce
//! the Python stack's collision verdicts and colliding-pair sets on every
//! PAR6 URDF variant, for self-collision and for the installation/program
//! keep-out layers.
//!
//! Fixtures: `tests/golden/collision/*.json`, regenerated by
//! `tests/golden/collision/gen_collision_fixtures.py` from
//! `pinokin.CollisionChecker` — the same Pinocchio+coal stack the Waldo
//! Commander client checks against, so this is a cross-stack conformance
//! test rather than a recording of this crate's own output.
//!
//! Collision verdicts are exact (a boolean and a set of names), so there is
//! no numeric tolerance to pick: the tolerance lives in the fixture cases,
//! which sit well clear of the contact boundary — the keep-out box swallows
//! the TCP by 60 mm, the standoff sphere clears it by ~110 mm, so a
//! convention slip or unit error flips the verdict rather than grazing it.
#![cfg(feature = "ffi")]

use std::collections::BTreeSet;
use std::path::PathBuf;
use std::time::Instant;

use serde::Deserialize;

use par6_kin::{Collision, GripperVariant, Layer, Shape, ShapeKind, NQ};

#[derive(Deserialize)]
struct Fixture {
    urdf: String,
    nq_full: usize,
    clearance: f64,
    robot_geoms: Vec<String>,
    self_pair_count: usize,
    robot_only: Vec<Case>,
    scenes: Vec<Scene>,
}

#[derive(Deserialize)]
struct Case {
    name: String,
    q: [f64; NQ],
    active: bool,
    pairs: Vec<[String; 2]>,
}

#[derive(Deserialize)]
struct Scene {
    name: String,
    installation: Vec<WireShape>,
    program: Vec<WireShape>,
    pair_count: usize,
    cases: Vec<Case>,
}

#[derive(Deserialize, Clone)]
struct WireShape {
    name: String,
    kind: String,
    params: Vec<f64>,
    pose: Vec<f64>,
    collision: bool,
    margin: Option<f64>,
}

impl WireShape {
    /// Through the real seam: the fixture's wire form becomes a
    /// [`par6_proto::Shape`] and is converted exactly as the server will.
    fn to_shape(&self) -> Shape {
        Shape::from_proto(&par6_proto::Shape {
            kind: self.kind.clone(),
            params: self.params.clone(),
            pose: self.pose.clone(),
            collision: self.collision,
            margin: self.margin,
            name: self.name.clone(),
        })
        .unwrap_or_else(|e| panic!("fixture shape {:?}: {e}", self.name))
    }
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

fn assets_dir() -> PathBuf {
    repo_root().join("assets/par6_description")
}

fn fixture_name(variant: GripperVariant) -> &'static str {
    match variant {
        GripperVariant::Flange => "par6_flange",
        GripperVariant::Msg => "par6_msg",
        GripperVariant::Ssg48 => "par6_ssg48",
    }
}

fn load_fixture(variant: GripperVariant) -> Fixture {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join(format!(
        "tests/golden/collision/{}.json",
        fixture_name(variant)
    ));
    let json = std::fs::read_to_string(&path).unwrap_or_else(|e| {
        panic!("cannot read {path:?}: {e}; run tests/golden/collision/gen_collision_fixtures.py")
    });
    serde_json::from_str(&json).expect("fixture JSON schema mismatch")
}

/// Colliding pairs as an order-independent set of sorted name couples —
/// pair enumeration order is an implementation detail, membership is not.
fn pair_set(report_pairs: impl Iterator<Item = (String, String)>) -> BTreeSet<(String, String)> {
    report_pairs
        .map(|(a, b)| if a <= b { (a, b) } else { (b, a) })
        .collect()
}

fn expected_pairs(case: &Case) -> BTreeSet<(String, String)> {
    pair_set(case.pairs.iter().map(|p| (p[0].clone(), p[1].clone())))
}

fn assert_case(label: &str, col: &mut Collision, case: &Case) {
    let report = col.check(&case.q, false).unwrap();
    let got = pair_set(
        report
            .pairs()
            .map(|(a, b)| (a.to_owned(), b.to_owned()))
            .collect::<Vec<_>>()
            .into_iter(),
    );
    let want = expected_pairs(case);
    assert_eq!(
        report.active(),
        case.active,
        "{label}/{}: verdict (got pairs {got:?})",
        case.name
    );
    assert_eq!(got, want, "{label}/{}: colliding pairs", case.name);

    // The boolean gate must agree with the full report — the planner uses
    // stop_at_first for its fast path.
    let quick = col.check(&case.q, true).unwrap();
    assert_eq!(
        quick.active(),
        case.active,
        "{label}/{}: stop_at_first verdict disagrees with the full check",
        case.name
    );
    if case.active {
        assert_eq!(
            quick.pair_count(),
            1,
            "{label}/{}: stop_at_first must report exactly one pair",
            case.name
        );
    }
}

#[test]
fn matches_python_reference_on_all_variants() {
    for variant in GripperVariant::ALL {
        let fx = load_fixture(variant);
        assert!(
            fx.urdf.ends_with(variant.urdf_relpath()),
            "{variant:?} fixture/table drift"
        );

        let label = fixture_name(variant);
        let mut col = Collision::load(&assets_dir(), variant, fx.clearance)
            .unwrap_or_else(|e| panic!("{label} load failed: {e}"));
        assert_eq!(col.nq_full(), fx.nq_full, "{label} model shape drift");
        assert_eq!(
            col.pair_count(),
            fx.self_pair_count,
            "{label} self-collision pair set drift"
        );

        // Self-collision, no world shapes.
        for case in &fx.robot_only {
            assert_case(label, &mut col, case);
        }

        // The clear cases must really be clear: a model whose home pose
        // self-collides is broken however well it matches a fixture.
        let home = fx
            .robot_only
            .iter()
            .find(|c| c.name == "home")
            .expect("fixture must carry the home pose");
        assert!(!home.active, "{label}: home pose must not self-collide");

        // Robot geometry names are what the colliding-pair report shows.
        for case in &fx.robot_only {
            for pair in &case.pairs {
                for name in pair {
                    assert!(
                        fx.robot_geoms.contains(name),
                        "{label}: unknown robot geometry {name:?}"
                    );
                }
            }
        }

        for scene in &fx.scenes {
            let install: Vec<Shape> = scene.installation.iter().map(WireShape::to_shape).collect();
            let program: Vec<Shape> = scene.program.iter().map(WireShape::to_shape).collect();
            col.set_layer(Layer::Installation, &install).unwrap();
            col.set_layer(Layer::Program, &program).unwrap();
            assert_eq!(
                col.pair_count(),
                scene.pair_count,
                "{label}/{}: collision pair count",
                scene.name
            );
            for case in &scene.cases {
                assert_case(&format!("{label}/{}", scene.name), &mut col, case);
            }
        }

        // Leave the world empty again for the next variant's assertions.
        col.set_layer(Layer::Installation, &[]).unwrap();
        col.set_layer(Layer::Program, &[]).unwrap();
        for case in &fx.robot_only {
            assert_case(&format!("{label}/cleared"), &mut col, case);
        }
    }
}

fn box_shape(name: &str, half: f64, at: [f64; 3], margin: Option<f64>) -> Shape {
    Shape {
        name: name.to_owned(),
        kind: ShapeKind::Box,
        params: [2.0 * half, 2.0 * half, 2.0 * half, 0.0],
        pose: [at[0], at[1], at[2], 0.0, 0.0, 0.0],
        collision: true,
        margin,
    }
}

/// waldoctl's layer contract: `SET_SHAPES` replaces the program layer and
/// leaves installation keep-outs standing, markers are not enforced, every
/// accepted replacement advances `scene_epoch`, and a rejected one changes
/// nothing.
#[test]
fn layers_are_independent_and_epoch_tracks_the_applied_world() {
    let fx = load_fixture(GripperVariant::Flange);
    let reach = fx
        .scenes
        .iter()
        .find(|s| s.name == "keepout_at_reach_tcp")
        .expect("fixture must carry the keep-out scene");
    let keepout = reach.program[0].to_shape();
    let q_reach = reach
        .cases
        .iter()
        .find(|c| c.name == "reach_out")
        .expect("keep-out scene must carry the reach_out case")
        .q;

    let mut col = Collision::load(&assets_dir(), GripperVariant::Flange, 0.0).unwrap();
    assert_eq!(col.scene_epoch(), 0);
    assert_eq!(col.clearance(), 0.0);
    assert!(!col.check(&q_reach, false).unwrap().active());

    // Installation keep-out: the arm's own floor, always in contact.
    let floor = Shape {
        name: "floor".to_owned(),
        kind: ShapeKind::Plane,
        params: [0.0, 0.0, 1.0, 0.02],
        pose: [0.0; 6],
        collision: true,
        margin: None,
    };
    assert_eq!(col.set_layer(Layer::Installation, &[floor]).unwrap(), 1);
    assert_eq!(
        col.set_layer(Layer::Program, std::slice::from_ref(&keepout))
            .unwrap(),
        2
    );

    let names = pair_set(
        col.check(&q_reach, false)
            .unwrap()
            .pairs()
            .map(|(a, b)| (a.to_owned(), b.to_owned()))
            .collect::<Vec<_>>()
            .into_iter(),
    );
    assert!(
        names.iter().any(|(a, b)| a == "floor" || b == "floor"),
        "installation layer must be enforced: {names:?}"
    );
    assert!(
        names.iter().any(|(a, b)| a == "keepout" || b == "keepout"),
        "program layer must be enforced: {names:?}"
    );

    // SET_SHAPES replaces the program layer only.
    assert_eq!(col.set_layer(Layer::Program, &[]).unwrap(), 3);
    let names = pair_set(
        col.check(&q_reach, false)
            .unwrap()
            .pairs()
            .map(|(a, b)| (a.to_owned(), b.to_owned()))
            .collect::<Vec<_>>()
            .into_iter(),
    );
    assert!(
        names.iter().any(|(a, b)| a == "floor" || b == "floor"),
        "clearing the program layer must not drop installation keep-outs: {names:?}"
    );
    assert!(
        !names.iter().any(|(a, b)| a == "keepout" || b == "keepout"),
        "cleared program shape still enforced: {names:?}"
    );

    // A marker (collision = false) is displayed, never enforced.
    let mut marker = keepout.clone();
    marker.name = "marker".to_owned();
    marker.collision = false;
    assert_eq!(col.set_layer(Layer::Program, &[marker]).unwrap(), 4);
    let names = pair_set(
        col.check(&q_reach, false)
            .unwrap()
            .pairs()
            .map(|(a, b)| (a.to_owned(), b.to_owned()))
            .collect::<Vec<_>>()
            .into_iter(),
    );
    assert!(
        !names.iter().any(|(a, b)| a == "marker" || b == "marker"),
        "visual-only marker was enforced: {names:?}"
    );

    // A rejected replacement leaves the enforced world and the epoch alone.
    col.set_layer(Layer::Program, &[keepout]).unwrap();
    let epoch = col.scene_epoch();
    let bad = Shape {
        name: "bad".to_owned(),
        kind: ShapeKind::Sphere,
        params: [-1.0, 0.0, 0.0, 0.0],
        pose: [0.0; 6],
        collision: true,
        margin: None,
    };
    assert!(
        col.set_layer(Layer::Program, &[bad]).is_err(),
        "a negative sphere radius must be refused"
    );
    assert_eq!(
        col.scene_epoch(),
        epoch,
        "a refused world must not advance scene_epoch"
    );
    let names = pair_set(
        col.check(&q_reach, false)
            .unwrap()
            .pairs()
            .map(|(a, b)| (a.to_owned(), b.to_owned()))
            .collect::<Vec<_>>()
            .into_iter(),
    );
    assert!(
        names.iter().any(|(a, b)| a == "keepout" || b == "keepout"),
        "a refused SET_SHAPES must leave the previous world enforced: {names:?}"
    );
}

/// A shape without its own margin inherits the model-wide clearance — the
/// "robot's global clearance applies" half of waldoctl's margin contract.
#[test]
fn model_clearance_applies_to_shapes_without_a_margin() {
    let fx = load_fixture(GripperVariant::Flange);
    let scene = fx
        .scenes
        .iter()
        .find(|s| s.name == "standoff_sphere_no_margin")
        .expect("fixture must carry the standoff scene");
    // The fixture parks this sphere ~110 mm clear of the reach_out TCP.
    let standoff = scene.program[0].to_shape();
    assert!(standoff.margin.is_none(), "the scene must have no override");
    let q_reach = scene.cases[0].q;

    for (clearance, want_hit) in [(0.0, false), (0.12, true)] {
        let mut col = Collision::load(&assets_dir(), GripperVariant::Flange, clearance).unwrap();
        assert_eq!(col.clearance(), clearance);
        col.set_layer(Layer::Program, std::slice::from_ref(&standoff))
            .unwrap();
        assert_eq!(
            col.check(&q_reach, false).unwrap().active(),
            want_hit,
            "clearance {clearance} against a shape ~110 mm away"
        );
    }
}

/// The planner's per-segment question: does the straight joint-space path
/// between two clear endpoints pass through a keep-out?
#[test]
fn segment_check_finds_the_sample_that_enters_a_keepout() {
    let mut col = Collision::load(&assets_dir(), GripperVariant::Flange, 0.0).unwrap();

    // A base sweep: the TCP traces an arc through the workspace while both
    // endpoints stay far from where it passes.
    let from = [1.2, -1.2708, 3.7416, 0.0, 0.5, 0.0];
    let to = [-1.2, -1.2708, 3.7416, 0.0, 0.5, 0.0];
    assert_eq!(
        col.check_segment(&from, &to, 24).unwrap(),
        None,
        "both endpoints and the path between them are clear without a world"
    );

    // A box straddling the midpoint's TCP: the endpoints stay clear, so
    // only sampling the interior can catch it.
    let mut mid = [0.0; NQ];
    for i in 0..NQ {
        mid[i] = 0.5 * (from[i] + to[i]);
    }
    let mut kin = par6_kin::Kin::load(&assets_dir(), GripperVariant::Flange).unwrap();
    let mut tcp = [0.0; 6];
    kin.tcp(&mid, &mut tcp);
    let wall = box_shape("wall", 0.04, [tcp[0], tcp[1], tcp[2]], None);
    col.set_layer(Layer::Program, std::slice::from_ref(&wall))
        .unwrap();

    assert!(
        !col.check(&from, false).unwrap().active(),
        "start of the segment must be clear"
    );
    assert!(
        !col.check(&to, false).unwrap().active(),
        "end of the segment must be clear"
    );
    let hit = col
        .check_segment(&from, &to, 24)
        .unwrap()
        .expect("segment sweeping the TCP through the box must be caught");
    assert!(
        (1..25).contains(&hit),
        "the colliding sample must be interior, got {hit}"
    );
}

#[test]
fn refuses_malformed_shapes_and_non_finite_configurations() {
    let mut col = Collision::load(&assets_dir(), GripperVariant::Flange, 0.0).unwrap();

    // Wire-level: a kind waldoctl does not define, and an arity mismatch.
    assert!(Shape::from_proto(&par6_proto::Shape {
        kind: "torus".to_owned(),
        params: vec![1.0, 2.0],
        pose: vec![0.0; 6],
        collision: true,
        margin: None,
        name: "t".to_owned(),
    })
    .is_err());
    assert!(Shape::from_proto(&par6_proto::Shape {
        kind: "box".to_owned(),
        params: vec![1.0, 2.0],
        pose: vec![0.0; 6],
        collision: true,
        margin: None,
        name: "b".to_owned(),
    })
    .is_err());
    assert!(Shape::from_proto(&par6_proto::Shape {
        kind: "box".to_owned(),
        params: vec![1.0, 2.0, 3.0],
        pose: vec![0.0; 3],
        collision: true,
        margin: None,
        name: "b".to_owned(),
    })
    .is_err());

    // Value-level, refused when the layer is applied.
    for bad in [
        Shape {
            name: "zero_box".to_owned(),
            kind: ShapeKind::Box,
            params: [0.1, 0.0, 0.1, 0.0],
            pose: [0.0; 6],
            collision: true,
            margin: None,
        },
        Shape {
            name: "nan_box".to_owned(),
            kind: ShapeKind::Box,
            params: [0.1, f64::NAN, 0.1, 0.0],
            pose: [0.0; 6],
            collision: true,
            margin: None,
        },
        Shape {
            name: "inf_pose".to_owned(),
            kind: ShapeKind::Sphere,
            params: [0.1, 0.0, 0.0, 0.0],
            pose: [f64::INFINITY, 0.0, 0.0, 0.0, 0.0, 0.0],
            collision: true,
            margin: None,
        },
        Shape {
            name: "nan_margin".to_owned(),
            kind: ShapeKind::Sphere,
            params: [0.1, 0.0, 0.0, 0.0],
            pose: [0.0; 6],
            collision: true,
            margin: Some(f64::NAN),
        },
        Shape {
            name: "zero_normal".to_owned(),
            kind: ShapeKind::Plane,
            params: [0.0, 0.0, 0.0, 1.0],
            pose: [0.0; 6],
            collision: true,
            margin: None,
        },
    ] {
        let name = bad.name.clone();
        assert!(
            col.set_layer(Layer::Program, &[bad]).is_err(),
            "{name} must be refused"
        );
    }

    // A configuration that is not a configuration: an explicit error, never
    // a fabricated "clear" verdict.
    for bad_q in [
        [f64::NAN, 0.0, 0.0, 0.0, 0.0, 0.0],
        [0.0, f64::INFINITY, 0.0, 0.0, 0.0, 0.0],
    ] {
        assert!(
            col.check(&bad_q, false).is_err(),
            "non-finite configuration must be an error"
        );
    }
}

/// The number the planner budgets against: what one collision check costs
/// per waypoint, broken down by what is in the world. Printed with
/// `--nocapture`; the assertion is a catastrophe guard, not a benchmark
/// gate (CI runners are shared and noisy).
///
/// The world content matters enormously, which is the point of reporting
/// it per scene rather than as one number: an unbounded half-space has no
/// bounding volume, so coal cannot prune it against a link's mesh BVH and
/// falls back to scanning every triangle.
#[test]
fn per_waypoint_check_cost_is_reported() {
    let assets = assets_dir();
    // A base sweep across the workspace — the shape of a real planned move.
    let from = [1.2, -1.2708, 3.7416, 0.0, 0.5, 0.0];
    let to = [-1.2, -1.2708, 3.7416, 0.0, 0.5, 0.0];
    let n = 100;
    let samples: Vec<[f64; NQ]> = (0..n)
        .map(|i| {
            let t = i as f64 / (n - 1) as f64;
            let mut q = [0.0; NQ];
            for j in 0..NQ {
                q[j] = from[j] + t * (to[j] - from[j]);
            }
            q
        })
        .collect();

    // Gated separately: an unbounded half-space is known to cost ~35 ms
    // (see ShapeKind::Plane), so it would swallow any regression in the
    // scenes the planner is actually expected to run fast.
    let mut worst_bounded = 0.0f64;
    let mut worst_bounded_scene = String::new();
    for variant in [GripperVariant::Flange, GripperVariant::Ssg48] {
        let fx = load_fixture(variant);
        let mut col = Collision::load(&assets, variant, 0.0).unwrap();

        let scenes: Vec<(&str, Vec<Shape>, Vec<Shape>)> =
            std::iter::once(("self only", Vec::new(), Vec::new()))
                .chain(fx.scenes.iter().map(|s| {
                    (
                        s.name.as_str(),
                        s.installation.iter().map(WireShape::to_shape).collect(),
                        s.program.iter().map(WireShape::to_shape).collect(),
                    )
                }))
                .collect();

        for (name, install, program) in scenes {
            col.set_layer(Layer::Installation, &install).unwrap();
            col.set_layer(Layer::Program, &program).unwrap();
            col.check(&samples[0], false).unwrap();

            let mut times = Vec::with_capacity(n);
            for q in &samples {
                let t0 = Instant::now();
                col.check(q, false).unwrap();
                times.push(t0.elapsed().as_secs_f64() * 1e6);
            }
            times.sort_by(|a, b| a.partial_cmp(b).unwrap());
            let mean = times.iter().sum::<f64>() / times.len() as f64;
            let unbounded = install
                .iter()
                .chain(&program)
                .any(|s| s.kind == ShapeKind::Plane);
            if !unbounded && mean > worst_bounded {
                worst_bounded = mean;
                worst_bounded_scene = format!("{}/{name}", fixture_name(variant));
            }
            println!(
                "{:<10} {:<28} {:>3} pairs: mean {:>8.1} us  p50 {:>8.1}  \
                 p99 {:>9.1}  max {:>9.1}{}",
                fixture_name(variant),
                name,
                col.pair_count(),
                mean,
                times[times.len() / 2],
                times[times.len() * 99 / 100],
                times[times.len() - 1],
                if unbounded { "  [unbounded shape]" } else { "" },
            );
        }
    }

    // Measured worst bounded scene is ~0.7 ms; 5 ms leaves room for a
    // loaded shared runner while still catching a lost-pruning regression,
    // which costs three orders of magnitude, not a factor of two.
    assert!(
        worst_bounded < 5_000.0,
        "{worst_bounded_scene} averaged {worst_bounded:.0} us per check — \
         bounded keep-outs must stay in the sub-millisecond range"
    );
}
