//! Golden conformance: [`Kin`] must reproduce the Python stack's numerics
//! (pinokin fk/jacobian/tcp-rpy, pin gravity) on every PAR6 URDF variant
//! to 1e-9 absolute.
//!
//! Fixtures: `tests/golden/kinematics/*.json`, regenerated by
//! `scripts/ffi/gen_fixtures.py`. Both sides load the same URDF into the
//! same Pinocchio release, so agreement is limited only by summation
//! order (~1e-15 scale); 1e-9 keeps wide margin while any convention slip
//! (frame, row order, rpy) shows up at ~1e-3 or worse.
#![cfg(feature = "ffi")]

use std::path::PathBuf;

use serde::Deserialize;

use par6_kin::{GripperVariant, IkOptions, IkOutcome, Kin, NQ};

const TOL: f64 = 1e-9;

#[derive(Deserialize)]
struct Fixture {
    urdf: String,
    ee_frame: String,
    nq_full: usize,
    cases: Vec<Case>,
}

#[derive(Deserialize)]
struct Case {
    q: [f64; NQ],
    fk: Vec<f64>,
    tcp: Vec<f64>,
    jac: Vec<f64>,
    tau: Vec<f64>,
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("../..")
        .canonicalize()
        .unwrap()
}

fn assets_dir() -> PathBuf {
    repo_root().join("assets/par6_description")
}

fn fixture_name(variant: GripperVariant) -> &'static str {
    match variant {
        GripperVariant::Flange => "par6_flange",
        GripperVariant::Msg => "par6_msg",
        GripperVariant::Ssg48 => "par6_ssg48",
    }
}

fn load_fixture(variant: GripperVariant) -> Fixture {
    let path = repo_root().join(format!(
        "tests/golden/kinematics/{}.json",
        fixture_name(variant)
    ));
    let json = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("cannot read {path:?}: {e}; run scripts/ffi/gen_fixtures.py"));
    serde_json::from_str(&json).expect("fixture JSON schema mismatch")
}

fn assert_close(label: &str, case_idx: usize, got: &[f64], want: &[f64]) {
    assert_eq!(got.len(), want.len(), "{label}[{case_idx}] length");
    for (i, (g, w)) in got.iter().zip(want).enumerate() {
        assert!(
            (g - w).abs() <= TOL,
            "{label}[case {case_idx}][{i}]: got {g:.15e}, want {w:.15e}, \
             diff {:.3e} > {TOL:.0e}",
            (g - w).abs()
        );
    }
}

#[test]
fn matches_python_reference_on_all_variants() {
    for variant in GripperVariant::ALL {
        let fx = load_fixture(variant);
        assert_eq!(
            fx.ee_frame,
            variant.tcp_frame(),
            "{variant:?} fixture/table drift"
        );
        assert!(
            fx.urdf.ends_with(variant.urdf_relpath()),
            "{variant:?} fixture/table drift"
        );

        let mut kin = Kin::load(&assets_dir(), variant)
            .unwrap_or_else(|e| panic!("{variant:?} load failed: {e}"));
        assert_eq!(kin.nq_full(), fx.nq_full, "{variant:?} model shape drift");

        let label = fixture_name(variant);
        let mut pose = [0.0; 16];
        let mut tcp = [0.0; 6];
        let mut jac = [0.0; 6 * NQ];
        let mut tau = [0.0; NQ];
        for (i, case) in fx.cases.iter().enumerate() {
            kin.fk(&case.q, &mut pose).unwrap();
            assert_close(&format!("{label}.fk"), i, &pose, &case.fk);
            kin.tcp(&case.q, &mut tcp);
            assert_close(&format!("{label}.tcp"), i, &tcp, &case.tcp);
            kin.jacobian(&case.q, &mut jac).unwrap();
            assert_close(&format!("{label}.jac"), i, &jac, &case.jac);
            kin.gravity(&case.q, &mut tau).unwrap();
            assert_close(&format!("{label}.tau"), i, &tau, &case.tau);
        }
    }
}

#[test]
fn ik_recovers_fixture_poses_and_reports_nonconvergence() {
    // The gripper variants exercise the padded-jaw path; flange the plain one.
    for variant in [GripperVariant::Flange, GripperVariant::Ssg48] {
        let fx = load_fixture(variant);
        let mut kin = Kin::load(&assets_dir(), variant).unwrap();

        let mut solved = 0usize;
        let mut q_out = [0.0; NQ];
        for case in fx.cases.iter().take(8) {
            let target: [f64; 16] = case.fk.clone().try_into().unwrap();
            // Perturb the known solution; DLS should walk back to the pose
            // (possibly via a different q — pose error is what matters).
            let mut seed = case.q;
            for (i, s) in seed.iter_mut().enumerate() {
                *s += 0.15 * if i % 2 == 0 { 1.0 } else { -1.0 };
            }
            let opts = IkOptions {
                max_iters: 200,
                tol: 1e-16, // |e|^2, so pose error ~1e-8 — tighter than the assert
                ..IkOptions::default()
            };
            if kin.ik(&seed, &target, &mut q_out, opts).unwrap() != IkOutcome::Converged {
                continue;
            }
            solved += 1;
            let mut pose = [0.0; 16];
            kin.fk(&q_out, &mut pose).unwrap();
            for (g, w) in pose.iter().zip(&target) {
                assert!(
                    (g - w).abs() < 1e-6,
                    "converged IK pose mismatch: {g} vs {w}"
                );
            }
        }
        assert!(
            solved >= 6,
            "{variant:?}: DLS should recover most mildly-perturbed poses, solved {solved}/8"
        );

        // A pose far outside the workspace must come back as an explicit
        // MaxIters — no panic, no false convergence claim.
        let unreachable: [f64; 16] = [
            1.0, 0.0, 0.0, 10.0, //
            0.0, 1.0, 0.0, 0.0, //
            0.0, 0.0, 1.0, 10.0, //
            0.0, 0.0, 0.0, 1.0,
        ];
        let outcome = kin
            .ik(&[0.0; NQ], &unreachable, &mut q_out, IkOptions::default())
            .unwrap();
        assert_eq!(
            outcome,
            IkOutcome::MaxIters,
            "{variant:?} unreachable target"
        );
    }
}

#[test]
fn nan_inputs_yield_nan_pose_not_panic() {
    // ForwardKin seam contract: NaN input channels may produce NaN outputs
    // ("pose unknown"), and nothing may panic or fabricate a pose.
    let mut kin = Kin::load(&assets_dir(), GripperVariant::Flange).unwrap();
    let mut q = [0.0; NQ];
    q[2] = f64::NAN;
    let mut tcp = [0.0; 6];
    kin.tcp(&q, &mut tcp);
    assert!(
        tcp.iter().all(|v| v.is_nan()),
        "expected all-NaN tcp, got {tcp:?}"
    );

    // NaN seed through IK: must terminate and must not claim convergence.
    let target: [f64; 16] = {
        let mut pose = [0.0; 16];
        kin.fk(&[0.0; NQ], &mut pose).unwrap();
        pose
    };
    let mut q_out = [0.0; NQ];
    let outcome = kin
        .ik(&q, &target, &mut q_out, IkOptions::default())
        .unwrap();
    assert_eq!(outcome, IkOutcome::MaxIters);
}
